In [51]:
import pandas as pd



In [5]:
df = pd.read_csv('realistic_kraljic_dataset.csv')

In [6]:
df

Product_ID       Product_Name Supplier_Region  Lead_Time_Days  \
0         P001     Semiconductors   South America              81   
1         P002     Semiconductors   South America               8   
2         P003        Pharma APIs            Asia              65   
3         P004     Semiconductors   South America              70   
4         P005  Lithium Batteries            Asia              15   
..         ...                ...             ...             ...   
995       P996        Printer Ink          Global              19   
996       P997  Cleaning Supplies          Global              21   
997       P998           Uniforms          Global              70   
998       P999        Printer Ink          Global              44   
999      P1000  Cleaning Supplies          Global              76   

     Order_Volume_Units  Cost_per_Unit  Supply_Risk_Score  \
0                   171         255.03                  5   
1                   763         380.33                  5   
2                   413         385.24                  4   
3                   882         287.64                  5   
4                   120         382.26                  4   
..                  ...            ...                ...   
995               19648          10.20                  2   
996               19143          15.30                  1   
997                5352          30.23                  1   
998               18070          30.73                  1   
999                9018          29.98                  1   

     Profit_Impact_Score  Environmental_Impact Single_Source_Risk  \
0                      5                     4                Yes   
1                      4                     4                Yes   
2                      5                     5                Yes   
3                      5                     5                Yes   
4                      4                     4                Yes   
..                   ...                   ...                ...   
995                    1                     1                 No   
996                    2                     1                 No   
997                    3                     2                 No   
998                    1                     2                 No   
999                    3                     1                 No   

    Kraljic_Category  
0          Strategic  
1          Strategic  
2          Strategic  
3          Strategic  
4          Strategic  
..               ...  
995     Non-Critical  
996     Non-Critical  
997     Non-Critical  
998     Non-Critical  
999     Non-Critical  

[1000 rows x 11 columns]

In [7]:
df.columns

Index(['Product_ID', 'Product_Name', 'Supplier_Region', 'Lead_Time_Days',
       'Order_Volume_Units', 'Cost_per_Unit', 'Supply_Risk_Score',
       'Profit_Impact_Score', 'Environmental_Impact', 'Single_Source_Risk',
       'Kraljic_Category'],
      dtype='object')

In [10]:
df.drop(['Product_ID','Product_Name','Supplier_Region'],axis=1,inplace=True)

In [11]:
df

Lead_Time_Days  Order_Volume_Units  Cost_per_Unit  Supply_Risk_Score  \
0                81                 171         255.03                  5   
1                 8                 763         380.33                  5   
2                65                 413         385.24                  4   
3                70                 882         287.64                  5   
4                15                 120         382.26                  4   
..              ...                 ...            ...                ...   
995              19               19648          10.20                  2   
996              21               19143          15.30                  1   
997              70                5352          30.23                  1   
998              44               18070          30.73                  1   
999              76                9018          29.98                  1   

     Profit_Impact_Score  Environmental_Impact Single_Source_Risk  \
0                      5                     4                Yes   
1                      4                     4                Yes   
2                      5                     5                Yes   
3                      5                     5                Yes   
4                      4                     4                Yes   
..                   ...                   ...                ...   
995                    1                     1                 No   
996                    2                     1                 No   
997                    3                     2                 No   
998                    1                     2                 No   
999                    3                     1                 No   

    Kraljic_Category  
0          Strategic  
1          Strategic  
2          Strategic  
3          Strategic  
4          Strategic  
..               ...  
995     Non-Critical  
996     Non-Critical  
997     Non-Critical  
998     Non-Critical  
999     Non-Critical  

[1000 rows x 8 columns]

In [12]:
# categorical data into num data

df['Single_Source_Risk'] = df['Single_Source_Risk'].map({'Yes':1,'No':0})

In [13]:
df

Lead_Time_Days  Order_Volume_Units  Cost_per_Unit  Supply_Risk_Score  \
0                81                 171         255.03                  5   
1                 8                 763         380.33                  5   
2                65                 413         385.24                  4   
3                70                 882         287.64                  5   
4                15                 120         382.26                  4   
..              ...                 ...            ...                ...   
995              19               19648          10.20                  2   
996              21               19143          15.30                  1   
997              70                5352          30.23                  1   
998              44               18070          30.73                  1   
999              76                9018          29.98                  1   

     Profit_Impact_Score  Environmental_Impact  Single_Source_Risk  \
0                      5                     4                   1   
1                      4                     4                   1   
2                      5                     5                   1   
3                      5                     5                   1   
4                      4                     4                   1   
..                   ...                   ...                 ...   
995                    1                     1                   0   
996                    2                     1                   0   
997                    3                     2                   0   
998                    1                     2                   0   
999                    3                     1                   0   

    Kraljic_Category  
0          Strategic  
1          Strategic  
2          Strategic  
3          Strategic  
4          Strategic  
..               ...  
995     Non-Critical  
996     Non-Critical  
997     Non-Critical  
998     Non-Critical  
999     Non-Critical  

[1000 rows x 8 columns]

In [16]:
df['Lead_Time_Days'].unique()

array([81,  8, 65, 70, 15, 84, 69, 68, 35, 87, 78, 41, 33, 10, 34, 38,  9,
        7, 62, 22, 73, 17, 66, 25, 31, 74, 54, 60, 12, 32, 57, 21, 53, 18,
       63, 40, 67, 80, 42, 29, 58, 13, 89, 37, 51, 23, 11, 27, 59, 83, 44,
       72, 14, 16, 20, 48, 45, 39, 61, 19, 75, 52, 46, 55, 24, 28, 86, 43,
       36, 56, 79, 64, 88, 77, 71, 30, 47, 49, 82, 50, 85, 76, 26])

In [17]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm  import SVC

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [18]:
df.columns

Index(['Lead_Time_Days', 'Order_Volume_Units', 'Cost_per_Unit',
       'Supply_Risk_Score', 'Profit_Impact_Score', 'Environmental_Impact',
       'Single_Source_Risk', 'Kraljic_Category'],
      dtype='object')

In [24]:
df.isnull().sum()

Lead_Time_Days          0
Order_Volume_Units      0
Cost_per_Unit           0
Supply_Risk_Score       0
Profit_Impact_Score     0
Environmental_Impact    0
Single_Source_Risk      0
Kraljic_Category        0
dtype: int64

In [19]:
x = df[['Lead_Time_Days', 'Order_Volume_Units', 'Cost_per_Unit',
       'Supply_Risk_Score', 'Profit_Impact_Score', 'Environmental_Impact',
       'Single_Source_Risk']]

In [20]:
y = df['Kraljic_Category']

In [21]:
x

Lead_Time_Days  Order_Volume_Units  Cost_per_Unit  Supply_Risk_Score  \
0                81                 171         255.03                  5   
1                 8                 763         380.33                  5   
2                65                 413         385.24                  4   
3                70                 882         287.64                  5   
4                15                 120         382.26                  4   
..              ...                 ...            ...                ...   
995              19               19648          10.20                  2   
996              21               19143          15.30                  1   
997              70                5352          30.23                  1   
998              44               18070          30.73                  1   
999              76                9018          29.98                  1   

     Profit_Impact_Score  Environmental_Impact  Single_Source_Risk  
0                      5                     4                   1  
1                      4                     4                   1  
2                      5                     5                   1  
3                      5                     5                   1  
4                      4                     4                   1  
..                   ...                   ...                 ...  
995                    1                     1                   0  
996                    2                     1                   0  
997                    3                     2                   0  
998                    1                     2                   0  
999                    3                     1                   0  

[1000 rows x 7 columns]

In [22]:
y

0         Strategic
1         Strategic
2         Strategic
3         Strategic
4         Strategic
           ...     
995    Non-Critical
996    Non-Critical
997    Non-Critical
998    Non-Critical
999    Non-Critical
Name: Kraljic_Category, Length: 1000, dtype: object

In [32]:
# call the models

model_knn = KNeighborsClassifier()
model_NB  = GaussianNB()
model_LR  = LogisticRegression()
model_svm = SVC()

In [33]:
# train test split

from sklearn.model_selection import train_test_split


In [34]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [35]:
x_train

Lead_Time_Days  Order_Volume_Units  Cost_per_Unit  Supply_Risk_Score  \
382              54                  60         258.63                  4   
994              36                7922          22.98                  1   
982              29               15055          29.48                  2   
47               67                 951         390.92                  4   
521              70                5440          89.95                  2   
..              ...                 ...            ...                ...   
767              86               16534          31.86                  1   
72               83                 184         313.36                  5   
908              83               13705          34.31                  1   
235              58                 289         236.42                  5   
37               57                 191         301.40                  5   

     Profit_Impact_Score  Environmental_Impact  Single_Source_Risk  
382                    2                     3                   1  
994                    1                     2                   0  
982                    2                     1                   0  
47                     4                     5                   1  
521                    4                     2                   1  
..                   ...                   ...                 ...  
767                    1                     2                   0  
72                     4                     5                   1  
908                    1                     1                   0  
235                    3                     5                   1  
37                     4                     5                   1  

[800 rows x 7 columns]

In [36]:
x_test

Lead_Time_Days  Order_Volume_Units  Cost_per_Unit  Supply_Risk_Score  \
507              48                4308          96.57                  2   
818              23                9378          14.63                  2   
452              47                 282         166.73                  5   
368              87                 123         119.97                  4   
242              40                 109         276.40                  5   
..              ...                 ...            ...                ...   
430              22                 110         112.51                  4   
874              58               12420          40.50                  2   
550              35                8954         102.99                  3   
608              25                8669          68.09                  2   
207              35                 433         258.37                  4   

     Profit_Impact_Score  Environmental_Impact  Single_Source_Risk  
507                    3                     2                   0  
818                    1                     2                   0  
452                    2                     3                   1  
368                    2                     4                   1  
242                    5                     5                   1  
..                   ...                   ...                 ...  
430                    3                     4                   1  
874                    1                     2                   0  
550                    5                     1                   0  
608                    4                     1                   0  
207                    5                     4                   1  

[200 rows x 7 columns]

In [37]:
y_train

382      Bottleneck
994    Non-Critical
982    Non-Critical
47        Strategic
521        Leverage
           ...     
767    Non-Critical
72        Strategic
908    Non-Critical
235       Strategic
37        Strategic
Name: Kraljic_Category, Length: 800, dtype: object

In [38]:
y_test

507        Leverage
818    Non-Critical
452      Bottleneck
368      Bottleneck
242       Strategic
           ...     
430      Bottleneck
874    Non-Critical
550        Leverage
608        Leverage
207       Strategic
Name: Kraljic_Category, Length: 200, dtype: object

In [39]:
x_train.shape,x_test.shape

((800, 7), (200, 7))

In [40]:
# training the model

model_knn.fit(x_train,y_train)

model_NB.fit(x_train,y_train)

model_LR.fit(x_train,y_train)

model_svm.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


SVC()

In [41]:
# testing the model

y_pred_knn = model_knn.predict(x_test)

y_pred_NB  = model_NB.predict(x_test)

y_pred_LR  = model_LR.predict(x_test)

y_pred_svm = model_svm.predict(x_test)

In [42]:
y_pred_knn

array(['Leverage', 'Non-Critical', 'Bottleneck', 'Bottleneck',
       'Bottleneck', 'Leverage', 'Bottleneck', 'Leverage', 'Bottleneck',
       'Strategic', 'Bottleneck', 'Strategic', 'Non-Critical',
       'Bottleneck', 'Non-Critical', 'Bottleneck', 'Strategic',
       'Strategic', 'Leverage', 'Bottleneck', 'Leverage', 'Bottleneck',
       'Leverage', 'Leverage', 'Bottleneck', 'Strategic', 'Strategic',
       'Leverage', 'Leverage', 'Strategic', 'Leverage', 'Leverage',
       'Leverage', 'Bottleneck', 'Bottleneck', 'Bottleneck', 'Strategic',
       'Non-Critical', 'Leverage', 'Leverage', 'Leverage', 'Leverage',
       'Strategic', 'Bottleneck', 'Strategic', 'Leverage', 'Leverage',
       'Strategic', 'Bottleneck', 'Non-Critical', 'Leverage', 'Strategic',
       'Leverage', 'Strategic', 'Strategic', 'Bottleneck', 'Non-Critical',
       'Leverage', 'Bottleneck', 'Leverage', 'Bottleneck', 'Strategic',
       'Bottleneck', 'Leverage', 'Non-Critical', 'Non-Critical',
       'Bottleneck', 'N

In [43]:
# Evaluation

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [47]:
print(classification_report(y_test,y_pred_knn))
print(confusion_matrix(y_test,y_pred_knn))
print(accuracy_score(y_test,y_pred_knn))

              precision    recall  f1-score   support

  Bottleneck       0.79      0.93      0.85        40
    Leverage       0.86      0.95      0.90        59
Non-Critical       0.92      0.80      0.86        45
   Strategic       0.94      0.82      0.88        56

    accuracy                           0.88       200
   macro avg       0.88      0.87      0.87       200
weighted avg       0.88      0.88      0.87       200

[[37  0  0  3]
 [ 0 56  3  0]
 [ 0  9 36  0]
 [10  0  0 46]]
0.875


In [48]:
print(classification_report(y_test,y_pred_NB))
print(confusion_matrix(y_test,y_pred_NB))
print(accuracy_score(y_test,y_pred_NB))

              precision    recall  f1-score   support

  Bottleneck       0.98      1.00      0.99        40
    Leverage       1.00      1.00      1.00        59
Non-Critical       1.00      1.00      1.00        45
   Strategic       1.00      0.98      0.99        56

    accuracy                           0.99       200
   macro avg       0.99      1.00      0.99       200
weighted avg       1.00      0.99      1.00       200

[[40  0  0  0]
 [ 0 59  0  0]
 [ 0  0 45  0]
 [ 1  0  0 55]]
0.995


In [49]:
print(classification_report(y_test,y_pred_LR))
print(confusion_matrix(y_test,y_pred_LR))
print(accuracy_score(y_test,y_pred_LR))

              precision    recall  f1-score   support

  Bottleneck       0.77      0.82      0.80        40
    Leverage       0.95      0.97      0.96        59
Non-Critical       0.95      0.93      0.94        45
   Strategic       0.87      0.82      0.84        56

    accuracy                           0.89       200
   macro avg       0.88      0.89      0.89       200
weighted avg       0.89      0.89      0.89       200

[[33  0  0  7]
 [ 0 57  2  0]
 [ 0  3 42  0]
 [10  0  0 46]]
0.89


In [50]:
print(classification_report(y_test,y_pred_svm))
print(confusion_matrix(y_test,y_pred_svm))
print(accuracy_score(y_test,y_pred_svm))

              precision    recall  f1-score   support

  Bottleneck       0.63      1.00      0.78        40
    Leverage       0.72      0.86      0.78        59
Non-Critical       0.96      0.56      0.70        45
   Strategic       0.82      0.59      0.69        56

    accuracy                           0.74       200
   macro avg       0.78      0.75      0.74       200
weighted avg       0.79      0.74      0.74       200

[[40  0  0  0]
 [ 0 51  1  7]
 [ 0 20 25  0]
 [23  0  0 33]]
0.745


In [ ]:
# In abpve dataset NB is the best model